name: 'Sign and Notarize'
description: 'Sign and Notarize your macOS applications'
inputs:
  input-path:
    description: 'Path to the input file or directory'
    required: true
  input-path-2:
    description: 'Path to the input file or directory'
    required: false
  macos-certificate:
    description: 'macOS certificate'
    required: false
  macos-certificate-id:
    description: 'macOS certificate ID'
    required: false
  macos-certificate-password:
    description: 'macOS certificate password'
    required: false
  macos-notarization-team:
    description: 'macOS notarization team id'
    required: false
  macos-notarization-user:
    description: 'macOS notarization user'
    required: false
  macos-notarization-password:
    description: 'macOS notarization password'
    required: false
  # windows-certificate:
  #   description: 'Windows certificate'
  #   required: false
  # windows-certificate-password:
  #   description: 'Windows certificate password'
  #   required: false

runs:
  using: "composite"
  steps:
    - name: Set variables
      id: vars
      run: |
        echo '${{ inputs.input-path }}'
        echo "macos-sign=${{ runner.os == 'macOS' && inputs.macos-certificate != '' && inputs.macos-certificate-id != '' && inputs.macos-certificate-password != '' }}" >> $GITHUB_OUTPUT
        echo "macos-notarize=${{ runner.os == 'macOS' && inputs.macos-notarization-team != '' && inputs.macos-notarization-user != '' && inputs.macos-notarization-password != '' }}" >> $GITHUB_OUTPUT
        #echo "windows-sign=${{ runner.os == 'Windows' && inputs.windows-certificate != '' && inputs.windows-certificate-password != '' }}" >> $GITHUB_OUTPUT
      shell: bash
    - name: setup python
      if: ${{ steps.vars.outputs.windows-sign == 'true' }} || ${{ steps.vars.outputs.macos-sign == 'true' }} || ${{ steps.vars.outputs.macos-notarize == 'true' }}
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    # Windows
    # - name: Set CodeSign Certificate Windows
    #   shell: powershell
    #   if: ${{ steps.vars.outputs.windows-sign == 'true' }}
    #   run: |
    #     Set-Content win_cert.txt -Value '${{ inputs.windows-certificate }}'
    #     certutil -decode win_cert.txt win_cert.pfx
    #     # print the list of the files in the current directory
    #     Get-ChildItem

    # - name: CodeSign Windows
    #   shell: bash
    #   if: ${{ steps.vars.outputs.windows-sign == 'true' }}
    #   run: |
    #     python $GITHUB_ACTION_PATH/windows-sign.py \
    #       --input_path='${{ inputs.input-path }}' \
    #       --cert_file=win_cert.pfx \
    #       --cert_pssw='${{ inputs.windows-certificate-password }}'
    #     # if input-path-2 is set
    #     if [ -n "${{ inputs.input-path-2 }}" ]; then
    #       python $GITHUB_ACTION_PATH/windows-sign.py \
    #         --input_path='${{ inputs.input-path-2 }}' \
    #         --cert_file=win_cert.pfx \
    #         --cert_pssw='${{ inputs.windows-certificate-password }}'
    #     fi

    # - name: Delete Windows certificate
    #   shell: bash
    #   if: ${{ steps.vars.outputs.windows-sign == 'true' }}
    #   run: |
    #     rm win_cert.pfx
    #     rm win_cert.txt

    # MacOS
    - name: Set CodeSign Certificate macOS
      if: ${{ steps.vars.outputs.macos-sign == 'true' }}
      uses: apple-actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ inputs.macos-certificate }}
        p12-password: ${{ inputs.macos-certificate-password }}

    - name: CodeSign macOS
      shell: bash
      if: ${{ steps.vars.outputs.macos-sign == 'true' }}
      run: |
        python $GITHUB_ACTION_PATH/macos-sign.py \
          --input_path='${{ inputs.input-path }}' \
          --cert_id='${{ inputs.macos-certificate-id }}'
        # if input-path-2 is set
        if [ -n "${{ inputs.input-path-2 }}" ]; then
          python $GITHUB_ACTION_PATH/macos-sign.py \
            --input_path='${{ inputs.input-path-2 }}' \
            --cert_id='${{ inputs.macos-certificate-id }}'
        fi

    - name: Set Notatization Credentials
      shell: bash
      if: ${{ steps.vars.outputs.macos-notarize == 'true' }}
      run: |
        echo "Setting notarization credentials..."
        python $GITHUB_ACTION_PATH/macos-notar-cred.py \
          --notarization_team='${{ inputs.macos-notarization-team }}' \
          --notarization_user='${{ inputs.macos-notarization-user }}' \
          --notarization_pssw='${{ inputs.macos-notarization-password }}'

    - name: Notarize macOS
      shell: bash
      if: ${{ steps.vars.outputs.macos-notarize == 'true' }}
      run: |
        python $GITHUB_ACTION_PATH/macos-notarize.py \
          --input_path='${{ inputs.input-path }}'
        # if input-path-2 is set
        if [ -n "${{ inputs.input-path-2 }}" ]; then
          python $GITHUB_ACTION_PATH/macos-notarize.py \
            --input_path='${{ inputs.input-path-2 }}'
        fi

